import type {
  DefinitionApplyState,
  DefinitionRollbackExecuteState,
  DefinitionRollbackPrepareState,
} from "../types.js";
import type { PermissionCenterState, PermissionLedgerRequestRecord } from "../permission-ledger.js";

/** Session identifier — a UUID v4 generated by the framework. */
export type SessionId = string;

export interface FocusElement {
  kind: "heading" | "paragraph" | "code-block" | "list-item";
  /** Index among siblings of the same kind in the file (0-based). */
  index: number;
  /** Truncated snippet (≤120 chars) for context. */
  text?: string;
  /** Slug or anchor id when kind === "heading". */
  anchor?: string;
  /** Nesting level — only meaningful for "heading". */
  level?: number;
}

export interface Focus {
  /** Workspace-relative path of the file the builder is viewing. */
  file?: string;
  element?: FocusElement;
}

export type Action =
  | { kind: "user-message"; text: string }
  | { kind: "click"; target: string; meta?: Record<string, unknown> };

export type ViewerRequest =
  | { kind: "navigate"; url: string }
  | { kind: "highlight"; selector: string }
  | { kind: "toast"; message: string; level?: "info" | "warn" | "error" };

export interface PermissionPrompt {
  id: string;
  tool: string;
  detail: Record<string, unknown>;
}

export interface PermissionResponse {
  id: string;
  decision: "allow" | "deny" | "allow-always";
}

export interface PermissionLedgerState {
  readonly pending: readonly PermissionLedgerRequestRecord[];
  readonly recent: readonly PermissionLedgerRequestRecord[];
  readonly permission_center?: PermissionCenterState;
}

/**
 * Session-scoped framework progress pushed from Agent/framework to Viewer.
 * These are state snapshots, not commands. Consumers should correlate snapshots
 * by `change_id` or `rollback_id`, render `phase` as fine-grained progress, and
 * render `status` as the coarse product state.
 */
export type FrameworkEvent =
  | { type: "definition-apply-state"; state: DefinitionApplyState }
  | { type: "definition-rollback-prepare-state"; state: DefinitionRollbackPrepareState }
  | { type: "definition-rollback-execute-state"; state: DefinitionRollbackExecuteState }
  | { type: "permission-ledger-state"; state: PermissionLedgerState };

/** Discriminated union; `dir` names the direction (viewer→agent / agent→viewer). */
export type WireEnvelope =
  | { dir: "v2a"; kind: "focus"; focus: Focus }
  | { dir: "v2a"; kind: "action"; action: Action }
  | { dir: "v2a"; kind: "permission-response"; response: PermissionResponse }
  | { dir: "a2v"; kind: "text"; turnId: string; partId: string; delta: string; done?: boolean }
  | { dir: "a2v"; kind: "viewer-request"; req: ViewerRequest }
  | { dir: "a2v"; kind: "permission-prompt"; prompt: PermissionPrompt }
  | { dir: "a2v"; kind: "framework-event"; event: FrameworkEvent }
  | { dir: "a2v"; kind: "state"; state: WorkspaceStateUpdate };

export interface WorkspaceStateUpdate {
  /** Workspace-relative path. */
  path: string;
  /** UTF-8 content. For v0 we only push text files; binary files are skipped. */
  content: string;
  /** Unix millis. */
  ts: number;
}
